import "./globals.css";
import Header from "./Header";

import ConfigureAmplifyClientSide from "@/componets/ConfigureAmplify";
import AuthProvider from "@/componets/AuthProvider";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  themeColor: "#ffffff",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <head />
      <body>
        <ConfigureAmplifyClientSide />
        <AuthProvider>
          <Header />
              {children}
        </AuthProvider>
      </body>
    </html>
  );
}
